### ISSUE TITLE
Suggestion: Don't ask for game play at the start of program

### ISSUE THREAD

**Issue by mayisa87** [ScribblesUrsa/Hang-Man#8]
https://github.com/ScribblesUrsa/Hang-Man/blob/29599ace76b128d2d2769788c68bf7132b34a80d/Program.cs#L33-L40

As already mentioned in WhatsApp, it makes no sense to me, to ask the user at the beginning of the game if he wants to play the game. If someone starts the program, we can assume, he/she wants to play it.

So remove while loop and just initialize your userChoice variable with YES.
`char userChoice = YES;`

This ensures that you will for sure at least enter your main while loop once.

**Comment by ScribblesUrsa** [comment]
I guess, I am one of the few that starts a game and decide not to play it @_@. My brain is weird lol. Bok ok, I will take it off
